"""add spotify name to rfid

Revision ID: bebf997f49d9
Revises: e4a4bb6a99c9
Create Date: 2023-11-08 19:05:49.879149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bebf997f49d9'
down_revision: Union[str, None] = 'e4a4bb6a99c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfid_numbers', sa.Column('spotify_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfid_numbers', 'spotify_name')
    # ### end Alembic commands ###
