"""create_rfid_table

Revision ID: e4a4bb6a99c9
Revises: 
Create Date: 2023-11-08 16:59:29.663364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a4bb6a99c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('spotify_token', sa.String(), nullable=True),
    sa.Column('spotify_token_type', sa.Enum('album', 'artist', 'playlist', 'track', 'other', name='tokenypeenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_numbers_id'), 'rfid_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_rfid_numbers_spotify_token'), 'rfid_numbers', ['spotify_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfid_numbers_spotify_token'), table_name='rfid_numbers')
    op.drop_index(op.f('ix_rfid_numbers_id'), table_name='rfid_numbers')
    op.drop_table('rfid_numbers')
    # ### end Alembic commands ###
